services:
  psql:
    image: postgis/postgis:15-3.4-alpine
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "order123"
      POSTGRES_DB: "order_db"
    ports:
      - "5433:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

volumes:
  psql_volume:



